# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    # The build command also creates a CNAME file as defined in package.json
    - run: npm run build --if-present

    - run: ls

    # - run: git checkout gh-pages || git checkout -b gh-pages
    # - run: git rm -rf .
    # - run: git show main:dist > dist.zip && unzip dist.zip && rm dist.zip
    # - run: git status

    - run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git push origin --delete gh-pages || true
        git switch -c gh-pages
        git status
        git add -f dist
        git status
        git commit -m "Update gh-pages with dist folder"
        git push -f origin gh-pages
        git checkout main
