# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    # Check out the gh-pages branch
    - run: git checkout gh-pages || git checkout -b gh-pages
    - run: git reset --hard

    # Remove existing files in the branch
    - run: git rm -rf .

    # Copy the contents of the dist folder from the main branch
    - run: git show --force main:dist/ | git apply --directory=.

    # Commit and push changes to the gh-pages branch
    - run: git config user.name "${GITHUB_ACTOR}"
    - run: git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - run: git add .
    - run: git commit -m "Update gh-pages"
    - run: git push origin gh-pages --force
